services:
  - type: web
    name: your-service-name
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - src: /*
        dest: /index.html
        status: 200
